### PR TITLE
Publish bundle and catalog on GitHub Container Registry

### PR DESCRIPTION
**Pull request by andreasgerstmayr**
This will need an update after #190 is merged.

### CODE REVIEW

**Comment by frzifus** [comment]
Seems we need to call regenerate one more time.

**Comment by andreasgerstmayr** [comment]
Ah, yep I'll do that after rebasing once #190 is merged.

**Comment by andreasgerstmayr** [comment]
This PR is ready for review now.

**Review by frzifus — APPROVED** [review]

**Comment by frzifus** [comment]
awesome :)

**Pull request merged**
