### PR TITLE
Rename template field in CRD to components

### PR DESCRIPTION
**Pull request by andreasgerstmayr**
Resolves: #229

### CODE REVIEW

**Review by frzifus — APPROVED** [review]
Oh yes and no :X

**Review by iblancasa — APPROVED** [review]

**Review by iblancasa — APPROVED** [review]

**Comment by andreasgerstmayr** [comment]
Because it's quite a breaking change, maybe let's wait a bit for additional reviews.

**Review by rubenvp8510 — APPROVED** [review]

**Review by pavolloffay — APPROVED** [review]

**Review by pavolloffay — CHANGES_REQUESTED** [review]
https://github.com/grafana/loki/blob/1b2f3e0cb2ebe2f012ebaa0731a0623ad6c537e2/operator/apis/loki/v1/lokistack_types.go#L725

We should prefer to be aligned with Loki CR and therefore rename the struct and not the CR field. 


Is there any strong argument to rename the CR field?

**Comment by andreasgerstmayr** [comment]
> Is there any strong argument to rename the CR field?

I'm fine either way, the only thing bothering me was that the struct attribute name (Components) was different to the json field name (template).

**Pull request closed without merging**
