### PR TITLE
Reload tenant configuration

### PR DESCRIPTION
**Pull request by iblancasa**
Solves #247

### CODE REVIEW

**Review by andreasgerstmayr — APPROVED** [review]
Looks great!
I think an additional e2e test would be a good idea, possibly in the same test as #215.

**Comment by iblancasa** [comment]
> Looks great! I think an additional e2e test would be a good idea, possibly in the same test as #215.

Thanks for your feedback @andreasgerstmayr!

@frzifus should I address this in a different PR or will you cover it in #329?

**Comment by iblancasa** [comment]
From this PR I found the `gateway.go` file is not covered by the unit tests at all.

**Review by frzifus — APPROVED** [review]

**Comment by frzifus** [comment]
> @frzifus should I address this in a different PR or will you cover it in https://github.com/os-observability/tempo-operator/pull/329?

Its not covered, but we can easily add it afterwards.

**Pull request merged**
